In [1]:
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

### Logistic Regression

In [4]:
l_score=cross_val_score(LogisticRegression(),iris.data,iris.target,cv=4)
l_score

C:\Users\Gaurav\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.97368421, 0.97368421, 0.94594595, 1.        ])

In [5]:
np.mean(l_score)

0.9733285917496444

###  SVC 

In [6]:
svm_score=cross_val_score(SVC(),iris.data,iris.target,cv=4)
svm_score

array([0.97368421, 1.        , 0.94594595, 0.97297297])

In [7]:
np.mean(svm_score)

0.9731507823613088

### Random Forest classifier 

In [8]:
rfc_score=cross_val_score(RandomForestClassifier(),iris.data,iris.target,cv=4)
rfc_score

array([0.97368421, 0.94736842, 0.94594595, 1.        ])

In [9]:
np.mean(rfc_score)

0.9667496443812233

### decision tree classifier

In [10]:
dtc_score=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target,cv=4)
dtc_score

array([0.97368421, 0.94736842, 0.94594595, 1.        ])

In [11]:
np.mean(dtc_score)

0.9667496443812233